SKILL_TAXONOMY = {
    "python": ["python", "py"],
    "java": ["java"],
    "javascript": ["javascript", "js"],
    "typescript": ["typescript", "ts"],
    "csharp": ["c#", "csharp", "c sharp"],
    "cpp": ["c++", "cpp"],
    "go": ["golang", "go"],
    "rust": ["rust"],
    "ruby": ["ruby"],
    "php": ["php"],
    "swift": ["swift"],
    "kotlin": ["kotlin"],
    "scala": ["scala"],
    "r": ["r language", "r programming"],
    "matlab": ["matlab"],
    "sql": ["sql", "structured query language"],
    "postgresql": ["postgres", "postgresql"],
    "mysql": ["mysql"],
    "sqlite": ["sqlite"],
    "mongodb": ["mongo", "mongodb"],
    "redis": ["redis"],
    "elasticsearch": ["elastic search", "elasticsearch"],
    "fastapi": ["fast api", "fastapi"],
    "django": ["django"],
    "flask": ["flask"],
    "react": ["react", "reactjs", "react js"],
    "nextjs": ["next js", "nextjs", "next.js"],
    "vue": ["vue", "vuejs", "vue js"],
    "angular": ["angular", "angularjs"],
    "svelte": ["svelte"],
    "redux": ["redux"],
    "tailwindcss": ["tailwind", "tailwindcss", "tailwind css"],
    "html": ["html", "html5"],
    "css": ["css", "css3"],
    "nodejs": ["node", "nodejs", "node js", "node.js"],
    "express": ["express", "expressjs"],
    "graphql": ["graphql"],
    "restapi": ["rest api", "restful api", "rest", "restful"],
    "websocket": ["websocket", "websockets"],
    "pytorch": ["torch", "pytorch"],
    "tensorflow": ["tensor flow", "tensorflow"],
    "keras": ["keras"],
    "scikitlearn": ["scikit learn", "scikitlearn", "sklearn"],
    "opencv": ["cv2", "opencv"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "matplotlib": ["matplotlib"],
    "seaborn": ["seaborn"],
    "plotly": ["plotly"],
    "xgboost": ["xgboost"],
    "lightgbm": ["lightgbm"],
    "catboost": ["catboost"],
    "mlflow": ["mlflow"],
    "huggingface": ["hugging face", "huggingface"],
    "transformers": ["transformers"],
    "spacy": ["spacy"],
    "nltk": ["nltk"],
    "langchain": ["langchain"],
    "llamaindex": ["llama index", "llamaindex"],
    "openai": ["openai"],
    "groq": ["groq"],
    "ollama": ["ollama"],
    "rag": ["retrieval augmented generation", "rag"],
    "faiss": ["faiss"],
    "chroma": ["chroma", "chromadb"],
    "pinecone": ["pinecone"],
    "docker": ["docker"],
    "kubernetes": ["k8s", "kubernetes"],
    "terraform": ["terraform"],
    "ansible": ["ansible"],
    "jenkins": ["jenkins"],
    "githubactions": ["github actions", "githubactions"],
    "gitlabci": ["gitlab ci", "gitlabci"],
    "awsecs": ["ecs", "aws ecs"],
    "awslambda": ["lambda", "aws lambda"],
    "aws": ["aws", "amazon web services"],
    "gcp": ["gcp", "google cloud", "google cloud platform"],
    "azure": ["azure", "microsoft azure"],
    "linux": ["linux", "ubuntu", "debian"],
    "bash": ["bash", "shell scripting", "shell"],
    "nginx": ["nginx"],
    "celery": ["celery"],
    "rabbitmq": ["rabbitmq"],
    "kafka": ["kafka", "apache kafka"],
    "airflow": ["apache airflow", "airflow"],
    "spark": ["apache spark", "spark"],
    "hadoop": ["hadoop"],
    "dbt": ["dbt"],
    "snowflake": ["snowflake"],
    "bigquery": ["big query", "bigquery"],
    "redshift": ["redshift"],
    "powerbi": ["power bi", "powerbi"],
    "tableau": ["tableau"],
    "excel": ["excel", "ms excel", "microsoft excel"],
    "jira": ["jira"],
    "agile": ["agile", "scrum"],
    "unittest": ["unit testing", "unittest", "pytest"],
    "pytest": ["pytest"],
    "selenium": ["selenium"],
    "playwright": ["playwright"],
    "cypress": ["cypress"],
    "jest": ["jest"],
    "vitest": ["vitest"],
    "reacttestinglibrary": ["react testing library"],
    "figma": ["figma"],
    "uiux": ["ui ux", "ui/ux", "ux", "user experience", "user interface"],
    "communication": ["communication", "communication skills"],
    "leadership": ["leadership", "team lead", "team leadership"],
    "problemsolving": ["problem solving", "problem-solving", "problem solving skills"]
}
